### ISSUE TITLE
Add Super Mario 3D All Stars

### ISSUE THREAD

**Issue by NoelleTGS** [Da532/NS-RPC#20]
Would be nice to have. Hopefully you're still updating this.

**Comment by Aethese** [comment]
He doesn't update this repo anymore but if you are in desperate need of an app like this you should check out [mine](https://github.com/Aethese/Switchence) lol. not as cool as this one but something else to use until he updates this one again.

and yes this is dirty self-promotion *sorry*

**Comment by TheHungryMonk** [comment]
agreed!
