### ISSUE TITLE
Trying to add a pin doesn't work 

### ISSUE THREAD

**Issue by Ariikitty** [Da532/NS-RPC#42]
I'm not sure if it's a case of it's not clear on how it works or if it's not working but after selecting the game I want to play and the message to display under it, clicking the pin and then switching to show pins says that there is no pins.

I'm on the 1.0.2 build for Windows

![image](https://github.com/Da532/NS-RPC/assets/45834971/a45a1d45-4aad-4355-a13b-1acee98f3de8)
![image](https://github.com/Da532/NS-RPC/assets/45834971/23bf02a5-78ac-45df-991c-5557ab53f1c3)

**Comment by Da532** [comment]
I am unsure what could be causing this behaviour aside from permissions.

Pins are saved in your home/user folder within a created NS-RPC directory, stored within a pinned.json file.
Please ensure the program has proper permissions.

I am pretty sure you are pinning things as intended, I really should write documentation, but just to make sure..
- select a game from the games list
- click the pin button
- switch list to ensure

If you are still experiencing problems let me know and I'll spin up a clean windows 10 enviroment for some testing.

**Comment by Da532** [comment]
Closing this as I have heard no response.
