### ISSUE TITLE
Some Games that are now very hot on the switch and I think will be great on NS RPC

### ISSUE THREAD

**Issue by tylabiebz** [Da532/NS-RPC#48]
New Nintendo Switch Games that hopefully make it to the NS RPC asap! These are new games that are very very hot and popular, some of them are third party magical ports that did change the value of the switch!

• Hogwarts Legacy
• Super Mario RPG
• Marvel Ultimate Alliance 3: The Black Order
• Batman: Arkham Asylum
• Batman: Arkham City
• Batman: Arkham Knight
All the other latest games even Bros Wonder is in there, great great app! Thank you✌🏻
I will be proud to show activity of these games in their definitive way through your app XD! Been playing these for hours and have seen that they are best sellers as well so figured I’ll put them here:)

**Comment by Da532** [comment]
As per request games have been added. Opening the application will pull the new games automatically :)

**Comment by tylabiebz** [comment]
Hey man thank you so much! you are the man! I'm actually not home but got a email notficiation and had to log in and send my love, appreciate it so much sir! And if you're a female I couldn't know so my mistake and you're the queen or king! appreciate it, I know it takes time < 3
